services:
  - type: web
    name: klassio-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: klassio-db
          property: connectionString
    plan: free

databases:
  - name: klassio-db
    databaseName: klassio
    user: klassio_user
    plan: free
